hubinter/ajax/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
	path('tags_by_theme/', tags_by_theme, name='tags_by_theme'),
	path('turn_off_marker/', turn_off_marker, name='turn_off_marker'),
	path('turn_on_marker/', turn_on_marker, name='turn_on_marker'),
	path('subscribe_user/', subscribe, name='subscribe_user'),
	path('unsubscribe_user/', unsubscribe, name='unsubscribe_user'),
	path('notify_user/', notify, name='notify'),
	path('not_notify_user/', not_notify, name='not_notify'),
	path('add_comment/', add_comment, name='add_comment'),
	path('change_avatar/', change_avatar, name='change_avatar'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hubinter/hubinter/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('videos.urls')),
    path('ajax/', include('ajax.urls')),
    path('account/', include('accounts.urls')),
    path('social_auth/', include('social_django.urls')),
    path('captcha/', include('captcha.urls'))
]

hubinter/videos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
	Home, VideoDetail, YoutubeVideoDetail, SearchVideos, 
	AddVideo, AddYoutubeVideo, DeleteVideo, DeleteYoutubeVideo, About, Contact
)


urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('video/<slug:slug>/', VideoDetail.as_view(), name='video'),
	path('youtube_video/<slug:slug>/', YoutubeVideoDetail.as_view(), name='youtube_video'),
	path('search/', SearchVideos.as_view(), name='search'),

	path('add_video/', AddVideo.as_view(), name='add_video'),
	path('add_youtube_video/', AddYoutubeVideo.as_view(), name='add_youtube_video'),

	path('delete_video/<slug:slug>/', DeleteVideo.as_view(), name='delete_video'),
	path('delete_youtube_video/<slug:slug>/', DeleteYoutubeVideo.as_view(), name='delete_youtube_video'),

	path('about/', About.as_view(), name='about'),
	path('contact/', Contact.as_view(), name='contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hubinter/videos/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
from django.shortcuts import reverse
from django.core.validators import FileExtensionValidator
from imagekit.models.fields import ImageSpecField
from imagekit.processors import ResizeToFit

import os
from delorean import Delorean



class Theme(models.Model):
	name = models.CharField(verbose_name='Theme', max_length=100, unique=True)
	slug = models.SlugField(verbose_name='Slug', unique=True)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		return super().save(*args, **kwargs)

	class Meta:
		verbose_name = 'Theme'
		verbose_name_plural = 'Themes'
		ordering = ['name']





class Tag(models.Model):
	name = models.CharField(verbose_name='Tag', max_length=50, unique=True)
	slug = models.SlugField(verbose_name='Slug', unique=True)
	theme = models.ForeignKey('Theme', on_delete=models.CASCADE, verbose_name='Theme')
	created_at = models.DateTimeField(verbose_name='Tag added', auto_now_add=True)

	def __str__(self):
		return self.name

	def get_created_at(self):
		delta = Delorean(datetime=self.created_at, timezone='Europe/Moscow')
		return delta.humanize().capitalize()

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		return super().save(*args, **kwargs)

	class Meta:
		verbose_name = 'Tag'
		verbose_name_plural = 'Tags'
		ordering = ['theme']




class Video(models.Model):
	title = models.CharField(verbose_name='Title', max_length=255, blank=False, null=False)
	slug = models.SlugField(verbose_name='Slug', max_length=300, unique=True)
	description = models.TextField(verbose_name='Description', max_length=2550)
	author = models.ForeignKey(
		settings.AUTH_USER_MODEL, default=None,
		on_delete=models.CASCADE, verbose_name='Author'
	)
	theme = models.ForeignKey('Theme', on_delete=models.PROTECT, verbose_name='Theme')
	tags = models.ManyToManyField('Tag', related_name='videos', verbose_name='Tags')
	created_at = models.DateTimeField(verbose_name='Published', auto_now_add=True)
	updated_at = models.DateTimeField(verbose_name='Updated', auto_now=True)
	preview = models.ImageField( # original preview
		upload_to='previews/%Y/%m/%d/', 
		validators=[ FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gmp']), ],
		verbose_name='Preview file', blank=True, default=os.path.join(settings.BASE_DIR, 'media/default_pictures/default_preview.png')
	)
	cropped_preview = ImageSpecField( 
		processors=[ResizeToFit(width=270, height=212, upscale=True, mat_color='#26292E')], 
		source='preview', format='PNG'
	)
	video = models.FileField(
		upload_to='videos/%Y/%m/%d/', 
		validators=[ FileExtensionValidator(allowed_extensions=['mp4', 'webm']), ],
		verbose_name='Video file'
	)
	views = models.PositiveIntegerField(verbose_name='Views', default=0)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('video', kwargs={'slug' : self.slug})

	def get_created_at(self):
		delta = Delorean(datetime=self.created_at, timezone='Europe/Moscow')
		return delta.humanize().capitalize()

	def get_updated_at(self):
		delta = Delorean(datetime=self.updated_at, timezone='Europe/Moscow')
		return delta.humanize().capitalize()

	class Meta:
		verbose_name = 'Video'
		verbose_name_plural = 'Videos'
		ordering = ['-created_at']




class YoutubeVideo(models.Model):
	iframe_code = models.TextField(verbose_name="Video's HTML code", blank=False, null=False)
	title = models.CharField(verbose_name='Youtube Title', max_length=255, blank=False, null=False)
	slug = models.SlugField(verbose_name='Slug', max_length=300, unique=True)
	added_by = models.ForeignKey(
		settings.AUTH_USER_MODEL, default=None,
		on_delete=models.CASCADE, verbose_name='Added by'
	)
	theme = models.ForeignKey('Theme', on_delete=models.PROTECT, verbose_name='Theme')
	tags = models.ManyToManyField('Tag', related_name='youtube_videos', verbose_name='Tags')
	added_at = models.DateTimeField(verbose_name='Added', auto_now_add=True)
	views = models.PositiveIntegerField(verbose_name='Views on Hubinter', default=0)
	preview = models.ImageField( # original preview
		upload_to='youtube_previews/%Y/%m/%d/',
		verbose_name='YouTube Preview', blank=True, 
		default=os.path.join(settings.BASE_DIR, 'media/default_pictures/default_preview.png')
	)
	cropped_preview = ImageSpecField( 
		processors=[ResizeToFit(width=270, height=212, upscale=True, mat_color='#26292E')], 
		source='preview', format='PNG'
	)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('youtube_video', kwargs={'slug' : self.slug})

	def get_added_at(self):
		delta = Delorean(datetime=self.added_at, timezone='Europe/Moscow')
		return delta.humanize().capitalize()




class Comment(models.Model):
	path = ArrayField(models.IntegerField())
	author = models.ForeignKey(
		settings.AUTH_USER_MODEL, editable=False,
		verbose_name='Author', on_delete=models.CASCADE
	)
	video = models.ForeignKey('Video', on_delete=models.CASCADE, editable=False, verbose_name='Video')
	text = models.TextField(verbose_name='Text', max_length=1000)
	created_at = models.DateTimeField(auto_now_add=True, verbose_name='Added')

	def __str__(self):
		return self.text[:100]

	def get_absolute_url(self):
		return reverse('video', kwargs={'slug' : self.video.slug})

	def get_created_at(self):
		delta = Delorean(datetime=self.created_at, timezone='Europe/Moscow')
		return delta.humanize().capitalize()

	def get_comment_offset(self):
		level = len(self.path) - 1
		if level >= 1: # maximum nesting level - 1 (like on YouTube)
			level = 1
		return level

	class Meta:
		verbose_name = 'Comment'
		verbose_name_plural = 'Comments'
		ordering = ['-created_at']

hubinter/videos/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

from captcha.fields import CaptchaField
from .models import Video, YoutubeVideo
from .utils import YT_Video_DataParser



class AddVideoForm(forms.ModelForm):
	"""Form to upload your own video"""

	def clean(self):
		"""Override clean method to make some custom validation"""
		self.is_theme_tags(self.cleaned_data)

	def is_theme_tags(self, data):
		"""Validating whether the selected tags belong to the selected theme"""
		for tag in data['tags']:
			if tag.theme != data['theme']:
				raise ValidationError(
					gettext_lazy('The {} tag does not relate to the {} theme.'.format(tag, data['theme']))
				)

	class Meta:
		model = Video
		fields = ('title', 'description', 'theme', 'tags', 'preview', 'video')
		widgets = {
			'title' : forms.TextInput(
        		attrs={
        			'class' : 'margin-20',
        			'placeholder' : 'Title...',
        		}
        	),
        	'description' : forms.Textarea(
        		attrs={
        			'class' : 'margin-50',
        			'placeholder' : 'Description...',
        			'rows' : 8,
        			'cols' : 40
        		}
        	),
        	'theme' : forms.Select(
        		attrs={
        			'class' : 'margin-20',
        		}
        	),
        	'tags' : forms.SelectMultiple(
        		attrs={
        			'class' : 'margin-50',
        		}
        	),
        	'preview' : forms.FileInput(
        		attrs={
        			'class' : 'margin-20',
					'style' : 'display: none !important;'
        		}
        	),
        	'video' : forms.FileInput(
        		attrs={
        			'class' : 'margin-50',
					'style': 'display: none !important;'
        		}
        	),
        }
		labels = {
			'title' : '',
			'description' : '',
			'theme' : 'Video Theme',
			'tags' : 'Tags (hold down “Control” to select more than one)',
			'preview' : 'Preview (Recommended: 1350x1060 px)',
			'video' : 'Video (.mp4 or .webm formats only)',
		}




class AddYoutubeVideoForm(forms.ModelForm):
	"""Form to add your video from YouTube on site"""

	def clean(self):
		self.is_theme_tags(self.cleaned_data)
		try:
			parser = YT_Video_DataParser(self.cleaned_data['iframe_code']) #!!! At this stage, this field contains the URL to the video, NOT iframe CODE !!!
		except ValidationError:
			raise
		else:
			parser.get_iframe_code() # save the iframe code in attribute before sending it to the server, to immediately raise a ValidationError in the form if smth is wrong
			self.cleaned_data['parser'] = parser

	def is_theme_tags(self, data):
		"""Validating whether the selected tags belong to the selected theme"""
		for tag in data['tags']:
			if tag.theme != data['theme']:
				raise ValidationError(
					gettext_lazy('The {} tag does not relate to the {} theme.'.format(tag, data['theme']))
				)

	class Meta:
		model = YoutubeVideo
		fields = ('iframe_code', 'theme', 'tags')
		widgets = {
			'iframe_code' : forms.TextInput(
        		attrs={
        			'class' : 'margin-20',
        			'placeholder' : 'Provide link to YouTube video...',
        		}
        	),
        	'theme' : forms.Select(
        		attrs={
        			'class' : 'margin-20',
        		}
        	),
        	'tags' : forms.SelectMultiple(
        		attrs={
        			'class' : 'margin-50',
        		}
        	)
        }
		labels = {
			'iframe_code' : '',
			'theme' : 'YouTube Video Theme',
			'tags' : 'Tags (hold down “Control” to select more than one)',
		}




class AddCommentForm(forms.Form):
	"""Form to add comment directly from the video-page"""

	parent_comment = forms.IntegerField(
		widget=forms.HiddenInput(
			attrs={
				"value" : "",
			}
		),
		required=False # if null, comment is not a response to someone else's
	)

	comment_text = forms.CharField(
		widget=forms.Textarea(
			attrs={
				'placeholder' : 'Write a comment...',
				'rows' : 1,
				'id' : 'contact_message',
				'class' : 'comment-text'
			}
		),
		max_length=1000,
		label='',
	)




class ContactForm(forms.Form):
	"""Form for writing feedback to the site's administrtion"""

	full_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				"placeholder" : "Full name...",
			}
		),
		min_length=4,
		max_length=256,
	)
	email = forms.EmailField(
		widget=forms.EmailInput(
			attrs={
				"placeholder" : "Your email adress...",
				"style" : "font-size: 16px !important;"
			}
		)
	)
	message = forms.CharField(
		widget=forms.Textarea(
			attrs={
				"rows" : 15,
				"cols" : 40,
				"placeholder" : "Your message..."
			}
		)
	)
	captcha = CaptchaField(error_messages={"invalid" : "The captcha was entered incorrectly!"})

hubinter/videos/templates/videos/add_video.html
{% extends "base.html" %}

{% block title %}Add video{% endblock title %}


{% block content %}
	<div class="container">
	    <!-- Title Page -->
	    <div class="row">
	        <div class="span12">
	            <div class="title-page">
	                <h2 class="title">Add Video</h2>
	                <h3 class="title-description">You can upload a new video or provide a link to your YouTube video.</h3>
	            </div>
	        </div>
	    </div>

	    {% include "inc/_switcher_add_video_forms.html" %}
	    
	    <div class="row">
			<!-- Form -->
			<div class="span12">    
				<form enctype="multipart/form-data" 
				action="
					{% if current_form_type == 'upload' %}
						{% url 'add_video' %}
					{% elif current_form_type == 'youtube' %}
						{% url 'add_youtube_video' %}
					{% else %}
						#
					{% endif %}				
					" 
				method="POST" class="add-video-form" id="contact-form">
					{% csrf_token %}
					{% if current_form_type == 'upload' %}						
						<p>{{ form.non_field_errors }}</p>
						{{ form.title.errors }}
						<p>{{ form.title }}</p>
						{{ form.description.errors }}
						<p>{{ form.description }}</p>
						{{ form.theme.errors }}
						<p>{{ form.theme }}</p>
						{{ form.tags.errors }}
						<p>{{ form.tags }}</p>
						{{ form.preview.errors }}
						<div class="add-video-input-block">
							<label id="upload-preview-input" for="id_preview">Select preview...</label>
							{{ form.preview }}
						</div>
						{{ form.video.errors }}
						<div class="add-video-input-block">
							<label id="upload-video-input" for="id_video">Select video...</label>
							{{ form.video }}
						</div>

						<script>
							// Display name of installed preview in input's label
							document.getElementById('id_preview').addEventListener('change', function() {
								var splittedFakePath = this.value.split('\\');
								console.log(splittedFakePath)
								if (!splittedFakePath[splittedFakePath.length - 1]) {
									document.getElementById('upload-preview-input').textContent = "Select preview..."
								}
								else {
									document.getElementById('upload-preview-input').textContent = splittedFakePath[splittedFakePath.length - 1];
								}
							});

							// Display name of installed video in input's label
							document.getElementById('id_video').addEventListener('change', function() {
								var splittedFakePath = this.value.split('\\');
								if (!splittedFakePath[splittedFakePath.length - 1]) {
									document.getElementById('upload-video-input').textContent = "Select video..."
								}
								else {
									document.getElementById('upload-video-input').textContent = splittedFakePath[splittedFakePath.length - 1];
								}
							});
						</script>
						
					{% else %}
						<p>{{ form.non_field_errors }}</p>
						{{ form.iframe_code.errors }}
						<p>{{ form.iframe_code }}</p>
						{{ form.theme.errors }}
						<p>{{ form.theme }}</p>
						{{ form.tags.errors }}
						<p>{{ form.tags }}</p>
					{% endif %}

					<input type="submit" class="submit-add-video" value="Save">
				</form>
			</div>     
	    </div>
	</div>

<script>
	// Show tags by current selected theme in add-video form
	select_theme_block = document.getElementById('id_theme')
	select_tag_block = document.getElementById('id_tags')

	// triggered when changing the selection
	select_theme_block.addEventListener('change', function() {
	    token = get_csrf_token();
	    $.ajax({
	        type: "POST",
	        url: location.protocol + '//' + location.host + '/ajax/tags_by_theme/',
	        data: {
	            'theme' : select_theme_block.options[select_theme_block.selectedIndex].text, // send chosen theme name
	            "csrfmiddlewaretoken" : token
	        },
	        success: function(response) {              
	            tag_list = merge_into_single_array(response) // get one list of tags by chosen theme
	            show_tags_by_theme(tag_list) // show only suitable ones
	        },
	        error: function(error) {
	            show_tags_by_theme("all") // if something went wrong, leave all tags visible
	        }
	    })
	});
</script>
{% endblock content %}

hubinter/videos/templates/videos/contact_feedback_msg.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body style="margin: 0; padding: 0;">

    <table align="center" border="0" cellpadding="0" cellspacing="0" width="320" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">
        <b>Full name: </b>{{ full_name }}
        <br>

        <b>E-mail: </b>{{ email }}
        <br>

        <b>Profile on Hubinter: </b><a href="{{ profile_url }}">{{ username }}</a>
        <br>
        <br>

        <b>Message:</b> 
        <p>{{ message }}</p>
    </table>

</body>
</html>

hubinter/videos/templates/videos/delete_video.html
{% extends "base.html" %}

{% block title %} Delete video {% endblock title %}


{% block content %}
	{% if video_type == "uploaded" %}
		<div class="delete-video-block">
			<div class="delete-video-preview">
				<img id="delete-video-preview" style="width: 40%;" src="{{ video.preview.url }}">
			</div>
			<div class="delete-video-title">
				<h3 style="margin-top: 20px;">{{ video.title }}</h3>
			</div>
		</div>
	{% else %}
		<div class="delete-video-block">
			<div class="delete-video-preview">
				<img id="delete-video-preview" style="width: 60%;" src="{{ video.preview.url }}">
			</div>
			<div class="delete-video-title">
				<h3 style="margin-top: 20px;">{{ video.title }}</h3>
			</div>
		</div>
	{% endif %}

	<form action="" method="POST" class="delete-video-form">
		{% csrf_token %}
		<p style="font-size: 18px;">Are you sure you want to delete this video?</p>
		<div class="delete-video-form-div">
			<input id="submit-deletion-button" class="button button-small" type="submit" value="Delete">
			{% if video_type == "uploaded" %}
				<a id="cancel-deletion-button" class="button button-small" href="{% url 'video' slug=video.slug %}">Cancel</a>
			{% else %}
				<a id="cancel-deletion-button" class="button button-small" href="{% url 'youtube_video' slug=video.slug %}">Cancel</a>
			{% endif %}
		</div>
	</form>

{% endblock content %}

hubinter/videos/templates/videos/email_notification_msg.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body style="margin: 0; padding: 0;">

    <table align="center" border="0" cellpadding="0" cellspacing="0" width="320" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">
        User <b>{{ author.username }}</b> published new video — "{{ video.title }}". 
        <br>
        Watch it soon 👇🏻
        <p><a href="{{ url }}">{{ url }}</a></p>
    </table>

</body>
</html>

hubinter/videos/templates/videos/index.html
{% extends 'base.html' %}
{% load sidebars %}


{% block title %} Hubinter {% endblock title %}
{% block alert %}{% endblock alert %}

{% block content %}
	
	{% include "inc/_searchbar.html" %}

    <!-- Portfolio Projects -->
    <div class="row">

		<div class="span3">
			{% get_theme_sidebar %}
			{% get_tag_sidebar %}
		</div>
        
        <div class="span9">
        	<div class="row">
            	<section id="projects">
                	<ul id="thumbs">
                    	
					    {% for video in all_videos %}
							<li class="item-thumbs span3 {{ video.theme | lower }} {% for tag in video.tags.all %} {{ tag | lower }}{% endfor %}">
						    	<a class="preview-block-link" href="{{ video.get_absolute_url }}">
						        	<img src="{{ video.cropped_preview.url }}" alt="{{ video.title }}" style="width: 100%;">
									<div class="tab-content">
										<div class="tab-pane fade active in" id="tab3">
											<div class="thumb-video-title-wrapper preview-video-title">
												{{ video.title | truncatewords:8 | truncatechars:75 }}
											</div>
											<p class="preview-video-title">
												<span class="red-text">
													{% if video.author %}
														{{ video.author | truncatechars:30 }}
													{% else %}
														{{ video.added_by | truncatechars:30 }}
													{% endif %}						
												</span>
												<br><br>
												<i><span>
													{% if video.get_created_at %}
														{{ video.get_created_at }}
													{% else %}
														{{ video.get_added_at }}
													{% endif %}
												</span></i>
												<br><br>
												<span class="yellow-text">{{ video.views }} views</span>
											</p>
										</div>
									</div>
								</a>
						    </li>
						{% endfor %}

                    </ul>
                </section>            
        	</div>
        	{% include "inc/_pagination.html" %}
        </div>

    </div>


	<script>
		current_link = document.getElementById("backend-sidebar-theme")
		// current_link.click();
	</script>
{% endblock %}

{# class="hover-wrap fancybox" #}

{# <span class="overlay-img"></span>
<span class="overlay-img-thumb font-icon-plus"></span> #}

hubinter/videos/templates/videos/video_search.html
{% extends 'base.html' %}


{% block title %}{% endblock title %}

{% block alert %}{% endblock alert %}


{% block content %}
	{% include "inc/_searchbar.html" %}

    <div class="span12">
    	<div class="row">
        	<section id="projects">
            	<ul id="thumbs">
                	
					    {% for video in found_videos %}
							<li class="item-thumbs span3 {{ video.theme | lower }} {% for tag in video.tags.all %} {{ tag | lower }}{% endfor %}">
						    	<a class="preview-block-link" href="{{ video.get_absolute_url }}">
						        	<img src="{{ video.cropped_preview.url }}" alt="{{ video.title }}" style="width: 100%;">
									<div class="tab-content">
										<div class="tab-pane fade active in" id="tab3">
											<p class="preview-video-title">
												{{ video.title | truncatewords:8 | truncatechars:75 }}
												<br><br>
												<span class="red-text">
													{% if video.author %}
														{{ video.author | truncatechars:30 }}
													{% else %}
														{{ video.added_by | truncatechars:30 }}
													{% endif %}						
												</span>
												<br><br>
												<i><span>
													{% if video.get_created_at %}
														{{ video.get_created_at }}
													{% else %}
														{{ video.get_added_at }}
													{% endif %}
												</span></i>
												<br><br>
												<span class="yellow-text">{{ video.views }} views</span>
											</p>
										</div>
									</div>
								</a>
						    </li>
						{% endfor %}

                </ul>
            </section>            
    	</div>
    	{% include "inc/_pagination.html" %}

    </div>
{% endblock content %}